In [40]:
import pandas as pd
import os.path 
import requests
from io import StringIO


url = "https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv"

# перевіряється наявність файлу 'movies.csv' в поточному каталозі. 
if not os.path.exists('/workspaces/HW6/movies.csv'):
    response = requests.get(url)
    df = pd.read_csv(StringIO(response.text))
    df.to_csv('movies.csv', index=False)
else:
    df = pd.read_csv('movies.csv')
    print('Файл вже існує')

Файл вже існує

In [41]:
df.head()

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008

In [42]:
#	2 завдання. Виконуються такі кроки:

#Виводяться назви стовпців за допомогою атрибуту columns.

#Виводяться типи даних кожного стовпця за допомогою атрибуту dtypes

df.columns

Index(['Film', 'Genre', 'Lead Studio', 'Audience score %', 'Profitability',
       'Rotten Tomatoes %', 'Worldwide Gross', 'Year'],
      dtype='str')

In [43]:
df.dtypes

Film                     str
Genre                    str
Lead Studio              str
Audience score %       int64
Profitability        float64
Rotten Tomatoes %      int64
Worldwide Gross          str
Year                   int64
dtype: object

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Film               77 non-null     str
 1   Genre              77 non-null     str
 2   Lead Studio        77 non-null     str
 3   Audience score %   77 non-null     int64
 4   Profitability      77 non-null     float64
 5   Rotten Tomatoes %  77 non-null     int64
 6   Worldwide Gross    77 non-null     str
 7   Year               77 non-null     int64
dtypes: float64(1), int64(3), str(4)
memory usage: 4.9 KB

77 - це рядки

In [45]:
df.describe()

       Audience score %  Profitability  Rotten Tomatoes %         Year
count         77.000000      77.000000          77.000000    77.000000
mean          63.727273       4.599483          46.701299  2009.077922
std           13.657113       8.031990          26.095001     1.354974
min           35.000000       0.000000           3.000000  2007.000000
25%           52.000000       1.751351          26.000000  2008.000000
50%           64.000000       2.642353          45.000000  2009.000000
75%           76.000000       5.103117          64.000000  2010.000000
max           89.000000      66.934000          96.000000  2011.000000

In [46]:
# 3.Скільки всього фільмів у наборі даних?

df_film_count = df['Film'].value_counts().sum()
print(df_film_count)

77

In [47]:
# 	4. Скільки фільмів є у наборі даних для кожного року?
df_year_count = df['Year'].value_counts()
print(df_year_count)

Year
2008    20
2010    20
2011    14
2009    12
2007    11
Name: count, dtype: int64

In [48]:
#5. Покажіть детальну інформацію про найменш та найбільш прибуткові фільми у наборі даних.

df_max_profitability_isin = df.loc[df['Profitability'].isin([df['Profitability'].max()])]
print("\nНайбільш прибутковий фільм :")
print(df_max_profitability_isin)

# Найменш прибутковий фільм
df_min_profitability = df.loc[df['Profitability'].isin([df['Profitability'].min()])]
print("\nНайменш прибутковий фільм:")
print(df_min_profitability)

Найбільш прибутковий фільм :
         Film  Genre  Lead Studio  Audience score %  Profitability  \
68  Fireproof  Drama  Independent                51         66.934

    Rotten Tomatoes % Worldwide Gross  Year
68                 40         $33.47   2008

Найменш прибутковий фільм:
                  Film    Genre  Lead Studio  Audience score %  Profitability  \
3         When in Rome   Comedy       Disney                44            0.0
33  Our Family Wedding   Comedy  Independent                49            0.0
57           Jane Eyre  Romance    Universal                77            0.0

    Rotten Tomatoes % Worldwide Gross  Year
3                  15         $43.04   2010
33                 14         $21.37   2010
57                 85         $30.15   2011

In [49]:
#6. Значення "Жанр" часом здається непослідовним; спробуйте знайти ці невідповідності та виправити їх

df['Genre'].unique()

<StringArray>
[  'Romance',    'Comedy',     'Drama', 'Animation',   'Fantasy',   'Romence',
     'Comdy',    'Action',   'romance',    'comedy']
Length: 10, dtype: str

In [50]:
df['Genre'] = df['Genre'].replace({'Romance': 'Romance', 'romance': 'Romance', 'Romence': 'Romance', 'comedy': 'Comedy', 'Comdy': 'Comedy'})
df['Genre'].unique()

<StringArray>
['Romance', 'Comedy', 'Drama', 'Animation', 'Fantasy', 'Action']
Length: 6, dtype: str

In [51]:
#	7. Збережіть (у новий файл CSV) 10 найкращих комедій за кількістю глядачів;  покажіть лише назву фільму, рік та студію.
best_comedy = df['Genre'] == 'Comedy'
best_ten_comedy = df[best_comedy].sort_values(by='Audience score %', ascending=False).head(10)
print(best_ten_comedy[['Film', 'Year', 'Lead Studio']])

                                  Film  Year   Lead Studio
54                          Knocked Up  2007     Universal
27                    Sex and the City  2008  Warner Bros.
76                (500) Days of Summer  2009           Fox
69                           Enchanted  2007        Disney
71                           Beginners  2011   Independent
44                       Marley and Me  2008           Fox
45                          Mamma Mia!  2008     Universal
46                          Mamma Mia!  2008     Universal
60  High School Musical 3: Senior Year  2008        Disney
30                            Penelope  2008        Summit

тут присутні дублікати до строки 45 і 46

In [39]:
#	Зберігається результат у новому CSV файлі.
with open('best_comedy.csv', 'w') as f:
    best_ten_comedy[['Film', 'Year', 'Lead Studio']].to_csv(f, index=False)